/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2016-06-09 06:51:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.PaginaMaestra;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import entidades.entUsuario;

public final class MasterIntranetHead_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("entidades.entUsuario");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("  <section id=\"container\" >\r\n");
      out.write("      <!-- **********************************************************************************************************************************************************\r\n");
      out.write("      TOP BAR CONTENT & NOTIFICATIONS\r\n");
      out.write("      *********************************************************************************************************************************************************** -->\r\n");
      out.write("      <!--header start-->\r\n");
      out.write("      <form >\r\n");
      out.write("      <header class=\"header black-bg\">\r\n");
      out.write("              <div class=\"sidebar-toggle-box\">\r\n");
      out.write("                  <div class=\"fa fa-bars tooltips\" data-placement=\"right\" data-original-title=\"Toggle Navigation\"></div>\r\n");
      out.write("              </div>\r\n");
      out.write("            <!--logo start-->\r\n");
      out.write("            <a href=\"frmIntranetUsuario.jsp\" class=\"logo\"><b>Intranet de Usuario</b></a>\r\n");
      out.write("      \r\n");
      out.write("            <div class=\"top-menu\">\r\n");
      out.write("            \r\n");
      out.write("            \t<ul class=\"nav pull-right top-menu\">\r\n");
      out.write("            \t\r\n");
      out.write("            \t<li>  ");

		HttpSession ses = request.getSession();
		if(ses.getAttribute("usuarito")==null){
			response.sendRedirect("frmCliente.jsp");
		}
		entUsuario u = (entUsuario)ses.getAttribute("usuarito");
	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t");

		out.print("<h3>"+u.getNombres()+ "  "+u.getApellidos()+"       .                     "+"</h3>");
	
      out.write(" </li>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("                    <li><a class=\"logout\" href=\"LoginIntranet.jsp\">Logout</a></li>\r\n");
      out.write("                      \r\n");
      out.write("            \t</ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </header>\r\n");
      out.write(" </form>\r\n");
      out.write("      <!--header end-->\r\n");
      out.write("      \r\n");
      out.write("      <!-- **********************************************************************************************************************************************************\r\n");
      out.write("      MAIN SIDEBAR MENU\r\n");
      out.write("      *********************************************************************************************************************************************************** -->\r\n");
      out.write("      <!--sidebar start-->\r\n");
      out.write("      <aside>\r\n");
      out.write("          <div id=\"sidebar\"  class=\"nav-collapse \">\r\n");
      out.write("              <!-- sidebar menu start-->\r\n");
      out.write("              <ul class=\"sidebar-menu\" id=\"nav-accordion\">\r\n");
      out.write("              \r\n");
      out.write("              \t  <p class=\"centered\"><a href=\"frmIntranetUsuario.jsp\"><img src=\"assets/img/logo-cabecera2.jpg\" class=\"img-circle\" width=\"60\"></a></p>\r\n");
      out.write("              \t  <h5 class=\"centered\">Ventas Online</h5>\r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("                  <li class=\"sub-menu\">\r\n");
      out.write("                      <a href=\"javascript:;\" >\r\n");
      out.write("                          <i class=\"fa fa-desktop\"></i>\r\n");
      out.write("                          <span>Equipos</span>\r\n");
      out.write("                      </a>\r\n");
      out.write("                      <ul class=\"sub\">\r\n");
      out.write("                          <li><a  href=\"frmListadoEquipos.jsp\">Listado de Equipos</a></li>\r\n");
      out.write("                          <li><a  href=\"frmNuevoEquipo.jsp\">Nuevo Equipo</a></li>\r\n");
      out.write("                           <li><a  href=\"frmMenuEditar.jsp\">Editar Equipo</a></li>\r\n");
      out.write("                            \r\n");
      out.write("                      </ul>\r\n");
      out.write("                  </li>\r\n");
      out.write("\r\n");
      out.write("                  <li class=\"sub-menu\">\r\n");
      out.write("                      <a href=\"javascript:;\" >\r\n");
      out.write("                          <i class=\"fa fa-cogs\"></i>\r\n");
      out.write("                          <span>Components</span>\r\n");
      out.write("                      </a>\r\n");
      out.write("                      <ul class=\"sub\">\r\n");
      out.write("                         <li><a  href=\"Hora.jsp\">Hora</a></li>\r\n");
      out.write("                          <li><a  href=\"calendar.jsp\">Calendario</a></li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"sub-menu\">\r\n");
      out.write("                      <a href=\"javascript:;\" >\r\n");
      out.write("                          <i class=\"fa fa-book\"></i>\r\n");
      out.write("                          <span>Empleados</span>\r\n");
      out.write("                      </a>\r\n");
      out.write("                      <ul class=\"sub\">\r\n");
      out.write("                          <li><a  href=\"frmNuevoUsuario.jsp\">Nuevo Uusario</a></li>\r\n");
      out.write("                         \r\n");
      out.write("                      </ul>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"sub-menu\">\r\n");
      out.write("                      <a href=\"javascript:;\" >\r\n");
      out.write("                          <i class=\"fa fa-tasks\"></i>\r\n");
      out.write("                          <span>Forms</span>\r\n");
      out.write("                      </a>\r\n");
      out.write("                      <ul class=\"sub\">\r\n");
      out.write("                          <li><a  href=\"form_component.html\">Form Components</a></li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"sub-menu\">\r\n");
      out.write("                      <a href=\"javascript:;\" >\r\n");
      out.write("                          <i class=\"fa fa-th\"></i>\r\n");
      out.write("                          <span>Data Tables</span>\r\n");
      out.write("                      </a>\r\n");
      out.write("                      <ul class=\"sub\">\r\n");
      out.write("                          <li><a  href=\"basic_table.html\">Basic Table</a></li>\r\n");
      out.write("                          <li><a  href=\"responsive_table.html\">Responsive Table</a></li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"sub-menu\">\r\n");
      out.write("                      <a href=\"javascript:;\" >\r\n");
      out.write("                          <i class=\" fa fa-bar-chart-o\"></i>\r\n");
      out.write("                          <span>Charts</span>\r\n");
      out.write("                      </a>\r\n");
      out.write("                      <ul class=\"sub\">\r\n");
      out.write("                          <li><a  href=\"morris.html\">Morris</a></li>\r\n");
      out.write("                          <li><a  href=\"chartjs.html\">Chartjs</a></li>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
