/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2016-06-09 05:50:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import entidades.entCliente;

public final class frmCatalogo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("entidades.entCliente");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Catalogo</title>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"css/reset.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"css/style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"css/skin-2.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"css/jquery.fancybox-1.3.4.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"css/tabs.css\">\r\n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=Cabin+Sketch:400,700' rel='stylesheet' type='text/css'>\r\n");
      out.write("    <script src=\"js/jquery-1.7.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.jcarousel.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jquery.fancybox-1.3.4.pack.js\"></script>\r\n");
      out.write("    <script src=\"js/tabs.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("\t\t$(document).ready(function(){\r\n");
      out.write("\t\t\tjQuery('#mycarousel-1, #mycarousel-2, #mycarousel-3, #mycarousel-4, #mycarousel-5, #mycarousel-6, #mycarousel-7').jcarousel({\r\n");
      out.write("\t\t\t\thorisontal: true,\r\n");
      out.write("\t\t\t\twrap:'circular',\r\n");
      out.write("\t\t\t\tscroll:1,\r\n");
      out.write("\t\t\t\teasing:'easeInOutBack',\r\n");
      out.write("\t\t\t\tanimation:1200\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$(\"a.plus\").fancybox({\r\n");
      out.write("\t\t\t\t'transitionIn'\t:\t'elastic',\r\n");
      out.write("\t\t\t\t'transitionOut'\t:\t'elastic',\r\n");
      out.write("\t\t\t\t'speedIn'\t\t:\t600, \r\n");
      out.write("\t\t\t\t'speedOut'\t\t:\t200, \r\n");
      out.write("\t\t\t\t'overlayShow'\t:\ttrue\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <!--==============================header=================================-->\r\n");
      out.write("\r\n");
      out.write("  <div class=\"header\">\r\n");
      out.write("  \t<div>\r\n");
      out.write("  \t \r\n");
      out.write("        <div class=\"subpages-nav\">\r\n");
      out.write("         \r\n");
      out.write("            <nav>  \r\n");
      out.write("            \r\n");
      out.write("                <ul class=\"menu\">\r\n");
      out.write("                \r\n");
      out.write("                    <li class=\"li-none\"><a href=\"Index.jsp\">Inicio</a></li>\r\n");
      out.write("                      <li><a href=\"frmLoginCliente.jsp\">Acceso</a></li>\r\n");
      out.write("                    <li class=\"current\"><a href=\"frmListaEquipoxMarca.jsp\">Modelos</a></li>\r\n");
      out.write("                    <li class=\"li-left li-none\"><a href=\"#\">Reportes</a></li>\r\n");
      out.write("                    <li><a href=\"LoginIntranet.jsp\">Intranet</a></li>\r\n");
      out.write("                    <li><a href=\"#\">Carrito</a></li>\r\n");
      out.write("                \r\n");
      out.write("                </ul>\r\n");
      out.write("                \r\n");
      out.write("     \r\n");
      out.write("                 \r\n");
      out.write("                \r\n");
      out.write("            </nav>\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("  </div>   \r\n");
      out.write("\r\n");
      out.write("     ");

		HttpSession ses = request.getSession();
		if(ses.getAttribute("cliente")==null){
			response.sendRedirect("frmCliente.jsp");
		}
		entCliente c = (entCliente)ses.getAttribute("cliente");
	
      out.write("\r\n");
      out.write("\t<h2>Bienvenido:</h2><h2>\r\n");
      out.write("\t");

		out.print("<h3>"+c.getNombres()+ "  "+c.getApellidos()+"</h3>");
	
	
      out.write("</h2>\r\n");
      out.write("  \r\n");
      out.write("    <section id=\"content\"><div class=\"ic\"></div>\r\n");
      out.write("    \t<div class=\"page3-row1 pad-2 tabs\">\r\n");
      out.write("        \t<div class=\"col-8\">\r\n");
      out.write("            \t<h2 class=\"h2 p2\">Marcas:</h2>\r\n");
      out.write("                <ul class=\"list-1 nav\">\r\n");
      out.write("                \t<li class=\"selected\"><a href=\"#tab-1\">Dell</a></li>\r\n");
      out.write("                    <li><a href=\"#tab-2\">HP</a></li>\r\n");
      out.write("                    <li><a href=\"#tab-3\">Lenovo</a></li>\r\n");
      out.write("                    <li><a href=\"#tab-4\">Sony</a></li>\r\n");
      out.write("                    <li><a href=\"#tab-5\">Toshiba</a></li>\r\n");
      out.write("                    <li><a href=\"#tab-6\">Acer</a></li>\r\n");
      out.write("                    <li><a href=\"#tab-7\">Samsung</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-9\">\r\n");
      out.write("            \t<h2 class=\"h3-2\">Modelos:</h2>\r\n");
      out.write("                <div id=\"tab-1\" class=\"tab-content gallery-photo\">\r\n");
      out.write("                   <div class=\"inner\">\r\n");
      out.write("                        <ul id=\"mycarousel-1\" class=\"jcarousel-skin-tango\">\r\n");
      out.write("                            <li><a class=\"plus\"     href=\"images/Dell-Inspiron-3000.jpg\"><img src=\"images/Dell-Inspiron-3000-min.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/Dell-Inspiron-3010.jpg\"><img src=\"images/Dell-Inspiron-3010-min.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/Dell-Inspiron-3080.jpg\"><img src=\"images/Dell-Inspiron-3080-min.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/Dell-Inspiron-3200.jpg\"><img src=\"images/Dell-Inspiron-3200-min.jpg\" alt=\"\"></a></li>\r\n");
      out.write("                            <li><a class=\"plus\"     href=\"images/Dell-Inspiron-3500.jpg\"><img src=\"images/Dell-Inspiron-3500-min.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/Dell-Inspiron-4000.jpg\"><img src=\"images/Dell-Inspiron-4000-min.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/Dell-Inspiron-5200.jpg\"><img src=\"images/Dell-Inspiron-5200-min.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/Dell-Inspiron-6020.jpg\"><img src=\"images/Dell-Inspiron-6020-min.jpg\" alt=\"\"></a></li>\r\n");
      out.write("                            <li><a class=\"plus\"     href=\"images/Dell-Inspiron-E410.jpg\"><img src=\"images/Dell-Inspiron-E410-min.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/dell1.jpg\"><img src=\"images/dell1-min.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/Dell-Inspiron-5521.JPG\"><img src=\"images/Dell-Inspiron-5521-min.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/Dell-AndyBrocoli.jpg\"><img src=\"images/Dell-AndyBrocoli-min.jpg\" alt=\"\"></a></li>\r\n");
      out.write("                            <li><a class=\"plus\"     href=\"images/Dell-Latitude-520.jpg\"><img src=\"images/Dell-Latitude-520-min.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/Dell-Ultrabook.jpg\"><img src=\"images/Dell-Ultrabook-min.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/Dell-Ultrabook-XPS.jpg\"><img src=\"images/Dell-Ultrabook-XPS-min.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/Dell-Vostro-3460.jpg\"><img src=\"images/Dell-Vostro-3460-min.jpg\" alt=\"\"></a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"tab-2\" class=\"tab-content gallery-photo\">\r\n");
      out.write("                   <div class=\"inner\">\r\n");
      out.write("                        <ul id=\"mycarousel-2\" class=\"jcarousel-skin-tango\">\r\n");
      out.write("                            <li><a class=\"plus\"     href=\"images/HP-Compaq-1022.jpg\"><img src=\"images/HP-Compaq-1022-min.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/HP-Compaq-4000.jpg\"><img src=\"images/HP-Compaq-4000-min.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/HP-Compaq-600.jpg\"><img src=\"images/HP-Compaq-600-min.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/HP-Compaq-800.jpg\"><img src=\"images/HP-Compaq-800-min.jpg\" alt=\"\"></a></li>\r\n");
      out.write("                            <li><a class=\"plus\"     href=\"images/HP-Compaq1234.jpg\"><img src=\"images/HP-Compaq1234-min.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/HP-Pavilion-DM3.jpg\"><img src=\"images/HP-Pavilion-DM3-min.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/HP-Pavilion-Dv5.jpg\"><img src=\"images/HP-Pavilion-Dv5-min.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/HP-Pavilion-Dv6-2.jpg\"><img src=\"images/HP-Pavilion-Dv6-2-min.jpg\" alt=\"\"></a></li>\r\n");
      out.write("                            <li><a class=\"plus\"     href=\"images/HP-Pavilion-Dv6.jpg\"><img src=\"images/HP-Pavilion-Dv6-min.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/HP-Pavilion-Dv7.jpg\"><img src=\"images/HP-Pavilion-Dv7-min.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/HP-Pavilion-G4.jpg\"><img src=\"images/HP-Pavilion-G4-min.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/HP-Pavilion-G5.jpg\"><img src=\"images/HP-Pavilion-G5-min.jpg\" alt=\"\"></a></li>\r\n");
      out.write("                            <li><a class=\"plus\"     href=\"images/HP-Pavillion-G.jpg\"><img src=\"images/HP-Pavillion-G-min.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/HP-ProBook4420.jpg\"><img src=\"images/HP-ProBook4420-min.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/HP-mini.jpg\"><img src=\"images/HP-mini-min.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/HP-EliteBook-840.jpg\"><img src=\"images/HP-EliteBook-840-min.jpg\" alt=\"\"></a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"tab-3\" class=\"tab-content gallery-photo\">\r\n");
      out.write("                   <div class=\"inner\">\r\n");
      out.write("                        <ul id=\"mycarousel-3\" class=\"jcarousel-skin-tango\">\r\n");
      out.write("                        \t<li><a class=\"plus\"     href=\"images/Lenovo-B470.jpg\"><img src=\"images/Lenovo-B470-min.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/Lenovo-B471.jpg\"><img src=\"images/Lenovo-B471-min.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/Lenovo-B590.jpg\"><img src=\"images/Lenovo-B590-min.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/Lenovo-G400.png\"><img src=\"images/Lenovo-G400-min.png\" alt=\"\"></a></li>\r\n");
      out.write("                            <li><a class=\"plus\"     href=\"images/lenovo-G95.jpg\"><img src=\"images/lenovo-G95-min.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/LENOVO-U350.jpg\"><img src=\"images/LENOVO-U350-min.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/Lenovo-Z500.jpg\"><img src=\"images/Lenovo-Z500-min.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/Lenovo-G50.jpg\"><img src=\"images/Lenovo-G50-min.jpg\" alt=\"\"></a></li>\r\n");
      out.write("                        \t <li><a class=\"plus\"     href=\"images/Lenovo-Gamer.jpg\"><img src=\"images/Lenovo-Gamer-min.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/Lenovo-Ideapad-Flex.jpg\"><img src=\"images/Lenovo-Ideapad-Flex-min.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/Lenovo-Ideapad-S200.jpg\"><img src=\"images/Lenovo-Ideapad-S200-min.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/lenovo-Ideapad-Y550.jpg\"><img src=\"images/lenovo-Ideapad-Y550-min.jpg\" alt=\"\"></a></li>\r\n");
      out.write("                            <li><a class=\"plus\"     href=\"images/Lenovo-Ideapad-Yoga.jpg\"><img src=\"images/Lenovo-Ideapad-Yoga-min.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/Lenovo-N500.jpg\"><img src=\"images/Lenovo-N500-min.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/lenovo-Esensial.jpg\"><img src=\"images/lenovo-Esensial-min.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/Lenovo-IdeaPad-500.jpg\"><img src=\"images/Lenovo-IdeaPad-500-min.jpg\" alt=\"\"></a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"tab-4\" class=\"tab-content gallery-photo\">\r\n");
      out.write("                   <div class=\"inner\">\r\n");
      out.write("                        <ul id=\"mycarousel-4\" class=\"jcarousel-skin-tango\">\r\n");
      out.write("                        \t<li><a class=\"plus\"     href=\"images/portfolio-12-big.jpg\"><img src=\"images/portfolio-12.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/portfolio-13-big.jpg\"><img src=\"images/portfolio-13.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/portfolio-14-big.jpg\"><img src=\"images/portfolio-14.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/portfolio-2-big.jpg\"><img src=\"images/portfolio-2.jpg\" alt=\"\"></a></li>\r\n");
      out.write("                             <li><a class=\"plus\"     href=\"images/portfolio-1-big.jpg\"><img src=\"images/portfolio-1.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/portfolio-2-big.jpg\"><img src=\"images/portfolio-2.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/portfolio-3-big.jpg\"><img src=\"images/portfolio-3.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/portfolio-4-big.jpg\"><img src=\"images/portfolio-4.jpg\" alt=\"\"></a></li>\r\n");
      out.write("                            <li><a class=\"plus\"     href=\"images/portfolio-5-big.jpg\"><img src=\"images/portfolio-5.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/portfolio-6-big.jpg\"><img src=\"images/portfolio-6.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/portfolio-7-big.jpg\"><img src=\"images/portfolio-7.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/portfolio-8-big.jpg\"><img src=\"images/portfolio-8.jpg\" alt=\"\"></a></li>\r\n");
      out.write("                            <li><a class=\"plus\"     href=\"images/portfolio-9-big.jpg\"><img src=\"images/portfolio-9.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/portfolio-10-big.jpg\"><img src=\"images/portfolio-10.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/portfolio-11-big.jpg\"><img src=\"images/portfolio-11.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/portfolio-1-big.jpg\"><img src=\"images/portfolio-1.jpg\" alt=\"\"></a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"tab-5\" class=\"tab-content gallery-photo\">\r\n");
      out.write("                   <div class=\"inner\">\r\n");
      out.write("                        <ul id=\"mycarousel-5\" class=\"jcarousel-skin-tango\">\r\n");
      out.write("                        \t <li><a class=\"plus\"     href=\"images/portfolio-1-big.jpg\"><img src=\"images/portfolio-1.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/portfolio-2-big.jpg\"><img src=\"images/portfolio-2.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/portfolio-3-big.jpg\"><img src=\"images/portfolio-3.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/portfolio-4-big.jpg\"><img src=\"images/portfolio-4.jpg\" alt=\"\"></a></li>\r\n");
      out.write("                            <li><a class=\"plus\"     href=\"images/portfolio-5-big.jpg\"><img src=\"images/portfolio-5.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/portfolio-6-big.jpg\"><img src=\"images/portfolio-6.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/portfolio-7-big.jpg\"><img src=\"images/portfolio-7.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/portfolio-8-big.jpg\"><img src=\"images/portfolio-8.jpg\" alt=\"\"></a></li>\r\n");
      out.write("                            <li><a class=\"plus\"     href=\"images/portfolio-9-big.jpg\"><img src=\"images/portfolio-9.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/portfolio-10-big.jpg\"><img src=\"images/portfolio-10.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/portfolio-11-big.jpg\"><img src=\"images/portfolio-11.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/portfolio-1-big.jpg\"><img src=\"images/portfolio-1.jpg\" alt=\"\"></a></li>\r\n");
      out.write("                            <li><a class=\"plus\"     href=\"images/portfolio-12-big.jpg\"><img src=\"images/portfolio-12.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/portfolio-13-big.jpg\"><img src=\"images/portfolio-13.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/portfolio-14-big.jpg\"><img src=\"images/portfolio-14.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/portfolio-2-big.jpg\"><img src=\"images/portfolio-2.jpg\" alt=\"\"></a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"tab-6\" class=\"tab-content gallery-photo\">\r\n");
      out.write("                   <div class=\"inner\">\r\n");
      out.write("                        <ul id=\"mycarousel-6\" class=\"jcarousel-skin-tango\">\r\n");
      out.write("                            <li><a class=\"plus\"     href=\"images/portfolio-12-big.jpg\"><img src=\"images/portfolio-12.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/portfolio-13-big.jpg\"><img src=\"images/portfolio-13.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/portfolio-14-big.jpg\"><img src=\"images/portfolio-14.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/portfolio-2-big.jpg\"><img src=\"images/portfolio-2.jpg\" alt=\"\"></a></li>\r\n");
      out.write("                            <li><a class=\"plus\"     href=\"images/portfolio-1-big.jpg\"><img src=\"images/portfolio-1.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/portfolio-2-big.jpg\"><img src=\"images/portfolio-2.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/portfolio-3-big.jpg\"><img src=\"images/portfolio-3.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/portfolio-4-big.jpg\"><img src=\"images/portfolio-4.jpg\" alt=\"\"></a></li>\r\n");
      out.write("                            <li><a class=\"plus\"     href=\"images/portfolio-5-big.jpg\"><img src=\"images/portfolio-5.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/portfolio-6-big.jpg\"><img src=\"images/portfolio-6.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/portfolio-7-big.jpg\"><img src=\"images/portfolio-7.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/portfolio-8-big.jpg\"><img src=\"images/portfolio-8.jpg\" alt=\"\"></a></li>\r\n");
      out.write("                            <li><a class=\"plus\"     href=\"images/portfolio-9-big.jpg\"><img src=\"images/portfolio-9.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/portfolio-10-big.jpg\"><img src=\"images/portfolio-10.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/portfolio-11-big.jpg\"><img src=\"images/portfolio-11.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/portfolio-1-big.jpg\"><img src=\"images/portfolio-1.jpg\" alt=\"\"></a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"tab-7\" class=\"tab-content gallery-photo\">\r\n");
      out.write("                   <div class=\"inner\">\r\n");
      out.write("                        <ul id=\"mycarousel-7\" class=\"jcarousel-skin-tango\">\r\n");
      out.write("                            <li><a class=\"plus\"     href=\"images/portfolio-5-big.jpg\"><img src=\"images/portfolio-5.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/portfolio-6-big.jpg\"><img src=\"images/portfolio-6.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/portfolio-7-big.jpg\"><img src=\"images/portfolio-7.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/portfolio-8-big.jpg\"><img src=\"images/portfolio-8.jpg\" alt=\"\"></a></li>\r\n");
      out.write("                            <li><a class=\"plus\"     href=\"images/portfolio-9-big.jpg\"><img src=\"images/portfolio-9.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/portfolio-10-big.jpg\"><img src=\"images/portfolio-10.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/portfolio-11-big.jpg\"><img src=\"images/portfolio-11.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/portfolio-1-big.jpg\"><img src=\"images/portfolio-1.jpg\" alt=\"\"></a></li>\r\n");
      out.write("                            <li><a class=\"plus\"     href=\"images/portfolio-12-big.jpg\"><img src=\"images/portfolio-12.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/portfolio-13-big.jpg\"><img src=\"images/portfolio-13.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/portfolio-14-big.jpg\"><img src=\"images/portfolio-14.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/portfolio-2-big.jpg\"><img src=\"images/portfolio-2.jpg\" alt=\"\"></a></li>\r\n");
      out.write("                            <li><a class=\"plus\"     href=\"images/portfolio-1-big.jpg\"><img src=\"images/portfolio-1.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/portfolio-2-big.jpg\"><img src=\"images/portfolio-2.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/portfolio-3-big.jpg\"><img src=\"images/portfolio-3.jpg\" alt=\"\"></a><a class=\"plus\"     href=\"images/portfolio-4-big.jpg\"><img src=\"images/portfolio-4.jpg\" alt=\"\"></a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>      \r\n");
      out.write("        </div>\r\n");
      out.write("    </section> \r\n");
      out.write("<!--==============================footer=================================-->\r\n");
      out.write(" <footer>\r\n");
      out.write("        <span><strong>© Sistema de Ventas de Laptops</strong>\r\n");
      out.write("        </span>\r\n");
      out.write("        </footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
