/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2016-06-09 06:05:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import entidades.entCliente;
import accesodatos.datEquipo;
import entidades.entEquipo;
import java.util.ArrayList;

public final class frmListaEquipoxMarca_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("accesodatos.datEquipo");
    _jspx_imports_classes.add("entidades.entEquipo");
    _jspx_imports_classes.add("entidades.entCliente");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Marcas</title>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"css/reset.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"css/style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"css/skin-2.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"css/jquery.fancybox-1.3.4.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"css/tabs.css\">\r\n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=Cabin+Sketch:400,700' rel='stylesheet' type='text/css'>\r\n");
      out.write("    <script src=\"js/jquery-1.7.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.jcarousel.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jquery.fancybox-1.3.4.pack.js\"></script>\r\n");
      out.write("    <script src=\"js/tabs.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("\t\t$(document).ready(function(){\r\n");
      out.write("\t\t\tjQuery('#mycarousel-1, #mycarousel-2, #mycarousel-3, #mycarousel-4, #mycarousel-5, #mycarousel-6, #mycarousel-7').jcarousel({\r\n");
      out.write("\t\t\t\thorisontal: true,\r\n");
      out.write("\t\t\t\twrap:'circular',\r\n");
      out.write("\t\t\t\tscroll:1,\r\n");
      out.write("\t\t\t\teasing:'easeInOutBack',\r\n");
      out.write("\t\t\t\tanimation:1200\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$(\"a.plus\").fancybox({\r\n");
      out.write("\t\t\t\t'transitionIn'\t:\t'elastic',\r\n");
      out.write("\t\t\t\t'transitionOut'\t:\t'elastic',\r\n");
      out.write("\t\t\t\t'speedIn'\t\t:\t600, \r\n");
      out.write("\t\t\t\t'speedOut'\t\t:\t200, \r\n");
      out.write("\t\t\t\t'overlayShow'\t:\ttrue\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!--[if lt IE 8]>\r\n");
      out.write("       <div style=' clear: both; text-align:center; position: relative;'>\r\n");
      out.write("         <a href=\"http://windows.microsoft.com/en-US/internet-explorer/products/ie/home?ocid=ie6_countdown_bannercode\">\r\n");
      out.write("           <img src=\"http://storage.ie6countdown.com/assets/100/images/banners/warning_bar_0000_us.jpg\" border=\"0\" height=\"42\" width=\"820\" alt=\"You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today.\" />\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("   \t\t<script type=\"text/javascript\" src=\"js/html5.js\"></script>\r\n");
      out.write("    \t<link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"css/ie.css\">\r\n");
      out.write("\t<![endif]-->\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  \r\n");
      out.write("  <!--==============================header=================================-->\r\n");
      out.write("  \r\n");
      out.write("<!--==============================content================================-->\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "PaginaMaestra/masterIntranetHEA.jsp", out, false);
      out.write("\r\n");
      out.write("   \t\r\n");
      out.write("     \r\n");
      out.write("\r\n");
      out.write("     \r\n");
      out.write("    <center>\r\n");
      out.write("    \r\n");
      out.write("\t");

	try{
		int idMarca = Integer.parseInt(request.getParameter("idMarca"));
		ArrayList<entEquipo> lista = datEquipo.ListarEquipoxMarca(idMarca);
		int numceldas = 0;
		HttpSession ses = request.getSession();
		for(int i=0;i<lista.size();i++){
			if(numceldas==0){
				out.print("<tr>");	
			}
			numceldas++;
			out.print("<td style='width:25%'>"+
					"<form method='post' action='sAgregar'>"+
					"<img src='images/"+lista.get(i).getImagen()+
					"' style='width:250px; height:250px'/><br/><br/>"+
					"<p style='color:#69e0e0; font-family:Arial;font-size:20px'>Modelo: "+
					lista.get(i).getModelo()+"</p><br/>"+				
					"<p style='color:#69e0e0; font-family:Arial;font-size:20px'>Serie:"+lista.get(i).getSerie()+"</p><br/>");
			if(ses.getAttribute("cliente")!=null){
				out.print("<p style='color:#69e0e0; font-family:Arial;font-size:20px'>"+
						"Precio: "+lista.get(i).getPrecio()+"</p><br/>");
			out.print("<input type='text' name='txtCant' value='1' style='width:70px'/>");					
			out.print("<input type='submit' name='btnAgrega' value='Comprar' "+
					"style='width:90px; background-color:yellow'/><br/><br/>");
			// 	Datos escondidos para leer del servlet
			out.print("<input type='hidden' name='Precio' value='"+
						lista.get(i).getPrecio()+"'/>");
			out.print("<input type='hidden' name='IDEquipo' value='"+
					lista.get(i).getIDEquipo()+"'/>");
			}
			
			out.print("</form></td>");			
			if(numceldas==4){
				out.print("</tr>");
				numceldas=0;
			}
		}
	}catch(Exception e){}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</center>\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "PaginaMaestra/masterExtranetFooter.jsp", out, false);
      out.write("           \r\n");
      out.write("               \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
