/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2016-06-09 05:53:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import entidades.entCliente;
import org.apache.tomcat.util.ExceptionUtils;
import entidades.*;
import accesodatos.*;

public final class frmRegistroCliente_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("entidades");
    _jspx_imports_packages.add("accesodatos");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.apache.tomcat.util.ExceptionUtils");
    _jspx_imports_classes.add("entidades.entCliente");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Registro Clientes</title>\r\n");
      out.write("     <link rel=\"stylesheet\" href=\"Boostrap/css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<h3></h3>\r\n");
      out.write("\t<br/>\r\n");
      out.write("\r\n");
      out.write("\t");


	if(request.getParameter("btnGuardar")!=null){
		try{
			entCliente p = new entCliente();
			p.setNombres(request.getParameter("txtNombre"));
			p.setApellidos(request.getParameter("txtApellido"));
			p.setDireccion(request.getParameter("txtDireccion"));
			p.setTelefono((request.getParameter("txtTelefono")));
			p.setUsuario(request.getParameter("txtUsuario"));
			p.setPassword(request.getParameter("Password"));
			p.setDNI(Integer.parseInt(request.getParameter("txtDNI")));
			
				
			boolean x = datCliente.InsertarCliente(p);
			if(x){
				out.print("<h3>Se inserto satisfactoriamente</h3>");
				response.sendRedirect("frmLoginCliente.jsp");
			}else{
				out.print("<h3>No se pudo insertar</h3>");
			}
		}catch(Exception e){
			out.print("<h3>"+e.getMessage()+"</h3>");
		}
	}
	if(request.getParameter("btnCancelar")!=null){
		response.sendRedirect("frmLoginCliente.jsp");
	}
	
	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t <div class=\"wrapper\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t<form><center>\r\n");
      out.write("\t<table>\r\n");
      out.write("\t<h1>Registro   de   Cliente</h1>\r\n");
      out.write("\t<br/><br/>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>Nombre:</td>\r\n");
      out.write("\t\t\t<td><input type=\"text\"  name=\"txtNombre\" placeholder=\"Nombres\" autofocus/></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>Apellidos:</td>\r\n");
      out.write("\t\t\t<td><input type=\"text\"  name=\"txtApellido\" placeholder=\"Apellidos\"/></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>Direccion:</td>\r\n");
      out.write("\t\t\t<td><input type=\"text\" placeholder=\"Direccion\" name=\"txtDireccion\"/></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>Telefono:</td>\r\n");
      out.write("\t\t\t<td><input type=\"text\" placeholder=\"Telefono\" name=\"txtTelefono\"/></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>Usuario:</td>\r\n");
      out.write("\t\t\t<td><input type=\"text\" placeholder=\"Usuario\" name=\"txtUsuario\"/></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>Password:</td>\r\n");
      out.write("\t\t\t<td><input type=\"text\" placeholder=\"Password\" name=\"Password\"/></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>DNI:</td>\r\n");
      out.write("\t\t\t<td><input type=\"text\" placeholder=\"DNI\" name=\"txtDNI\"/></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t<button type=\"submit\" id=\"login-button\" name=\"btnGuardar\">Guardar</button>\r\n");
      out.write("\t\t<button type=\"submit\" name=\"btnCancelar\">Cancelar</button>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("\t</table>\r\n");
      out.write("\t</center>\r\n");
      out.write("\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\r\n");
      out.write("\t<ul class=\"bg-bubbles\">\r\n");
      out.write("\t\t<li></li>\r\n");
      out.write("\t\t<li></li>\r\n");
      out.write("\t\t<li></li>\r\n");
      out.write("\t\t<li></li>\r\n");
      out.write("\t\t<li></li>\r\n");
      out.write("\t\t<li></li>\r\n");
      out.write("\t\t<li></li>\r\n");
      out.write("\t\t<li></li>\r\n");
      out.write("\t\t<li></li>\r\n");
      out.write("\t\t<li></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t\r\n");
      out.write("\t <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>\r\n");
      out.write("\r\n");
      out.write("        <script src=\"Boostrap/js/index.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
