/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2016-06-09 06:31:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import entidades.entCliente;
import entidades.entOrdenPed;
import java.util.ArrayList;

public final class frmVenta_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("entidades.entOrdenPed");
    _jspx_imports_classes.add("entidades.entCliente");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\t<title>Insert title here</title>\r\n");
      out.write("\t<meta charset=\"utf-8\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"css/reset.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"css/style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"css/slider.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"css/skin.css\">\r\n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=Cabin+Sketch:400,700' rel='stylesheet' type='text/css'>\r\n");
      out.write("    <script src=\"js/jquery-1.7.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("    <script src=\"js/tms-0.4.1.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.jcarousel.min.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("\t\t$(document).ready(function(){\r\n");
      out.write("\t\t\t$('.slider')._TMS({\r\n");
      out.write("\t\t\t\tshow:0,\r\n");
      out.write("\t\t\t\tpauseOnHover:false,\r\n");
      out.write("\t\t\t\tanteriorBu:false,\r\n");
      out.write("\t\t\t\tsiguienteBu:false,\r\n");
      out.write("\t\t\t\tplayBu:false,\r\n");
      out.write("\t\t\t\tduration:700,\r\n");
      out.write("\t\t\t\tpreset:'fade',\r\n");
      out.write("\t\t\t\tpagination:'.pags',\r\n");
      out.write("\t\t\t\tpagNums:false,\r\n");
      out.write("\t\t\t\tslideshow:7000,\r\n");
      out.write("\t\t\t\tnumStatus:false,\r\n");
      out.write("\t\t\t\tbanners:false,// fromLeft, fromRight, fromTop, fromBottom\r\n");
      out.write("\t\t\t\twaitBannerAnimation:false,\r\n");
      out.write("\t\t\t\tprogressBar:false\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\tjQuery('#mycarousel').jcarousel({\r\n");
      out.write("\t\t\t\thorisontal: true,\r\n");
      out.write("\t\t\t\twrap:'circular',\r\n");
      out.write("\t\t\t\tscroll:1,\r\n");
      out.write("\t\t\t\teasing:'easeInOutBack',\r\n");
      out.write("\t\t\t\tanimation:1200\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!--[if lt IE 8]>\r\n");
      out.write("       <div style=' clear: both; text-align:center; position: relative;'>\r\n");
      out.write("         <a href=\"http://windows.microsoft.com/en-US/internet-explorer/products/ie/home?ocid=ie6_countdown_bannercode\">\r\n");
      out.write("           <img src=\"http://storage.ie6countdown.com/assets/100/images/banners/warning_bar_0000_us.jpg\" border=\"0\" height=\"42\" width=\"820\" alt=\"You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today.\" />\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("   \t\t<script type=\"text/javascript\" src=\"js/html5.js\"></script>\r\n");
      out.write("    \t<link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"css/ie.css\">\r\n");
      out.write("\t<![endif]-->\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "PaginaMaestra/masterIntranetHEA.jsp", out, false);
      out.write("\t\r\n");
      out.write("\t<h3>Carrito de Compras</h3>\r\n");
      out.write("\t<table border=\"1\" style='width:100%'>\r\n");
      out.write("\t<thead style=\"background-color: yellow\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>Codigo</th>\r\n");
      out.write("\t\t\t<th>Descripcion</th>\r\n");
      out.write("\t\t\t<th>Cantidad</th>\r\n");
      out.write("\t\t\t<th>Precio</th>\r\n");
      out.write("\t\t\t<th>Descuento</th>\r\n");
      out.write("\t\t\t<th>Sub total</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</thead>\r\n");
      out.write("\t<tbody>\r\n");
      out.write("\t");

	HttpSession ses = request.getSession();
	entCliente c= (entCliente)ses.getAttribute("cliente");
	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t     <tr><td>Codigo:</td><td>");
      out.print(c.getIDCliente() );
      out.write("</td></tr>\r\n");
      out.write("\t      <tr><td>RUC:</td><td>");
      out.print(c.getNombres() );
      out.write("</td></tr>\r\n");
      out.write("\t       <tr><td>Razon Social:</td><td>");
      out.print(c.getApellidos() );
      out.write("</td></tr>\r\n");
      out.write("\t         <tr><td>Direccion:</td><td>");
      out.print(c.getDNI() );
      out.write("</td></tr>\r\n");
      out.write("\t       \r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t");

	
	ArrayList<entOrdenPed> lista = (ArrayList<entOrdenPed>)ses.getAttribute("Venta");
	for(int i=0;i<lista.size();i++){
		out.print("<tr>");
		out.print("<td>"+lista.get(i).getEquipo().getIDEquipo()+"</td>");
		out.print("<td>"+lista.get(i).getCantidad()+"</td>");
		out.print("<td>"+lista.get(i).getPrecio_Unitario()+"</td>");
		out.print("<td>"+lista.get(i).getDescuento()+"</td>");
	
		out.print("<td><img src='images/"+
						lista.get(i).getEquipo().getImagen()+
				"' style='width:20px; height:20px'/></td>");
		out.print("</tr>");
	}
	
      out.write("\r\n");
      out.write("\t</tbody>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<br/>\r\n");
      out.write("\t<form method=\"post\" action=\"sGuardarPedido\">\r\n");
      out.write("\tTarjeta:<select name=\"cboTarjeta\">\r\n");
      out.write("             <option value=\"1\">Visa</option>\t\r\n");
      out.write("              <option value=\"2\">MasterCard</option>\t\r\n");
      out.write("               <option value=\"3\">CMR</option>\t\r\n");
      out.write("\t</select><br><br/>\r\n");
      out.write("\tUsuario:<input type=\"text\" name=\"txtUsuarioTarjeta\"/><br> <br/>\r\n");
      out.write("\tNumero:<input type=\"text\" name=\"txtNumeroTarjeta\"/><br> <br/>\r\n");
      out.write("\t<input type=\"submit\" value=\"Guardar Pedido\"/> \r\n");
      out.write("\t</form>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "PaginaMaestra/masterExtranetFooter.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
