/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2016-06-09 05:50:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Vision_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Mision:</title>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"css/reset.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"css/style.css\">\r\n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=Cabin+Sketch:400,700' rel='stylesheet' type='text/css'>\r\n");
      out.write("    <script src=\"js/jquery-1.7.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("\t<!--[if lt IE 8]>\r\n");
      out.write("       <div style=' clear: both; text-align:center; position: relative;'>\r\n");
      out.write("         <a href=\"http://windows.microsoft.com/en-US/internet-explorer/products/ie/home?ocid=ie6_countdown_bannercode\">\r\n");
      out.write("           <img src=\"http://storage.ie6countdown.com/assets/100/images/banners/warning_bar_0000_us.jpg\" border=\"0\" height=\"42\" width=\"820\" alt=\"You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today.\" />\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("   \t\t<script type=\"text/javascript\" src=\"js/html5.js\"></script>\r\n");
      out.write("    \t<link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"css/ie.css\">\r\n");
      out.write("\t<![endif]-->\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <!--==============================header=================================-->\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("  \t<div>\r\n");
      out.write("        <div class=\"subpages-nav\">\r\n");
      out.write("            <nav>  \r\n");
      out.write("                <ul class=\"menu\">\r\n");
      out.write("                          <li class=\"current li-none\"><a href=\"Index.jsp\">Inicio</a></li>\r\n");
      out.write("                    <li><a href=\"frmLoginCliente.jsp\">Acceso</a></li>\r\n");
      out.write("                    <li><a href=\"frmListaEquipoxMarca.jsp\">Modelos</a></li>\r\n");
      out.write("                    <li class=\"li-left li-none\"><a href=\"#\">Reportes</a></li>\r\n");
      out.write("                  <li><a href=\"#\">Intranet</a></li>\r\n");
      out.write("                    <li><a href=\"#\">Carrito</a></li>\r\n");
      out.write("                     \r\n");
      out.write("                </ul>\r\n");
      out.write("                \r\n");
      out.write("            </nav>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>   \r\n");
      out.write("\r\n");
      out.write("<!--==============================content================================-->\r\n");
      out.write("    <section id=\"content\"><div class=\"ic\"></div>\r\n");
      out.write("    \t<div class=\"pad-1\">\r\n");
      out.write("            <div class=\"page2-row1\">\r\n");
      out.write("                <div class=\"col-4\">\r\n");
      out.write("                    <h2 class=\"h2 p2\">Mas Informacion:</h2>\r\n");
      out.write("                    <div class=\"wrap\">\r\n");
      out.write("                        <img src=\"images/mision.png\" alt=\"\" class=\"img-border img-indent\">\r\n");
      out.write("                        <div class=\"extra-wrap\">\r\n");
      out.write("                          <p class=\"p1\"><i>La laptop perfecta depende de las necesidades informaticas de aquel que la describa.Los nuevos <a href=\"marcas.jsp\" class=\"link\" target=\"_blank\">modelos</a> de laptops ofrecen una diversidad de opciones que se ajustan a las exigencias tecnologicas de los usuarios, entregando un producto  \r\n");
      out.write("de buena calidad &amp; un buen funcionamiento. </i></p>\r\n");
      out.write("<p>Nos diferenciamos en el mercado por ofrecer a nuestros clientes un equipo de alta calidad lo que garantiza la efectividad, rapidez, eficiencia. </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"col-5\">\r\n");
      out.write("                    <h3 class=\"h3 p2\">Exhibition &amp; awards:</h3>\r\n");
      out.write("                    <ul class=\"list-2\">\r\n");
      out.write("                       <center><img src=\"images/mision3.jpg\" alt=\"\" class=\"img-border img-indent\">\r\n");
      out.write("                       </center>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div> \r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("           <div class=\"pad-2\">\r\n");
      out.write("            <div class=\"page2-row2\">\r\n");
      out.write("                <div class=\"col-6\">\r\n");
      out.write("                    <h2 class=\"h2 p2\">Mision:</h2>\r\n");
      out.write("                    <div class=\"wrap\">\r\n");
      out.write("                        <img src=\"images/mision2.jpg\" alt=\"\" class=\"img-border img-indent\">\r\n");
      out.write("                        <div class=\"extra-wrap\">\r\n");
      out.write("                           <br/><br/><br/> <p class=\"p1\"><i>Generar relaciones de largo plazo con nuestros clientes, garantizando respuestas rapidas y eficientes, afrontando con exito los desafios cada vez mas exigentes que el mercado presenta, buscando la autosuperacion constante. </i></p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write(" \r\n");
      out.write("  <div class=\"col-8\">\r\n");
      out.write("                   \r\n");
      out.write("                    <ul class=\"list-2\">\r\n");
      out.write("                       <center><img src=\"images/mision5.jpg\" alt=\"\" class=\"img-border img-indent\">\r\n");
      out.write("                       </center>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div> \r\n");
      out.write(" \r\n");
      out.write("            \r\n");
      out.write("                <div class=\"pad-3\">\r\n");
      out.write("            <div class=\"page2-row3\">\r\n");
      out.write("                <div class=\"col-4\">\r\n");
      out.write("                    <h2 class=\"h2 p2\">Vision</h2>\r\n");
      out.write("                    <div class=\"wrap\">\r\n");
      out.write("                        <img src=\"images/mision4.jpg\" alt=\"\" class=\"img-border img-indent\">\r\n");
      out.write("                        <div class=\"extra-wrap\">\r\n");
      out.write("                           <br/><br/><br/> <p class=\"p1\"><i>Ser la empresa lider en el Peru en bridar servicios(venta de laptops) logrando el desarrollo del sector empresarial y generar nuevas alianazas estrategicas y sobretodo satisfacer las necesidades de nuestros clientes. </i></p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"col-1\">\r\n");
      out.write("                   \r\n");
      out.write("                    <ul class=\"list-2\">\r\n");
      out.write("                       <center><img src=\"images/mision6.jpg\" alt=\"\" class=\"img-border img-indent\">\r\n");
      out.write("                       </center>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div> \r\n");
      out.write("    </section> \r\n");
      out.write("<!--==============================footer=================================-->\r\n");
      out.write("    <footer>\r\n");
      out.write("        <span><strong>© Sistema de Ventas de Laptops</strong>\r\n");
      out.write("        </span>\r\n");
      out.write("        </footer>           \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
